export const allQuestions = {
  1: [
    {
      text: "Qual é a função principal dos verbos em uma frase?",
      options: [
        "Indicar qualidades dos substantivos",
        "Expressar ação, estado, mudança ou fenômeno",
        "Conectar palavras na frase",
        "Modificar outros verbos",
      ],
      correctAnswer: "Expressar ação, estado, mudança ou fenômeno",
      hint: "Pense nos exemplos: correr (ação), estar (estado), envelhecer (mudança), chover (fenômeno).",
    },
    {
      text: "Quais são as três conjugações verbais em português?",
      options: [
        "1ª (-ar), 2ª (-er), 3ª (-ir)",
        "1ª (-er), 2ª (-ir), 3ª (-or)",
        "1ª (-ir), 2ª (-ar), 3ª (-er)",
        "1ª (-or), 2ª (-ar), 3ª (-er)",
      ],
      correctAnswer: "1ª (-ar), 2ª (-er), 3ª (-ir)",
      hint: "Pense nos verbos 'falar', 'comer' e 'partir'.",
    },
    {
      text: "O que são verbos defectivos?",
      options: [
        "Verbos que não possuem todas as conjugações",
        "Verbos que possuem duas formas corretas de conjugação",
        "Verbos que não variam em pessoa e número",
        "Verbos que só existem no infinitivo",
      ],
      correctAnswer: "Verbos que não possuem todas as conjugações",
      hint: "Pense em verbos como 'abolir' ou 'falir', que não são usados em todas as formas.",
    },
    {
      text: "Qual é a diferença entre verbos regulares e irregulares?",
      options: [
        "Regulares seguem um padrão de conjugação, irregulares não",
        "Regulares só existem no presente, irregulares em todos os tempos",
        "Regulares são mais comuns, irregulares são raros",
        "Regulares têm uma sílaba, irregulares têm mais de uma",
      ],
      correctAnswer: "Regulares seguem um padrão de conjugação, irregulares não",
      hint: "Compare a conjugação de 'falar' com a de 'fazer'.",
    },
    {
      text: "O que caracteriza um verbo de ligação?",
      options: [
        "Expressa uma ação do sujeito",
        "Liga o sujeito a uma característica ou estado",
        "Necessita de um objeto direto",
        "Sempre termina em '-ar'",
      ],
      correctAnswer: "Liga o sujeito a uma característica ou estado",
      hint: "Pense em verbos como 'ser', 'estar', 'permanecer'.",
    },
    {
      text: "Qual é a função do modo subjuntivo?",
      options: [
        "Expressar certezas e fatos",
        "Dar ordens ou fazer pedidos",
        "Expressar possibilidades, desejos ou dúvidas",
        "Indicar ações no passado",
      ],
      correctAnswer: "Expressar possibilidades, desejos ou dúvidas",
      hint: "É usado em frases como 'Talvez eu vá' ou 'Espero que ele venha'.",
    },
    {
      text: "O que são verbos abundantes?",
      options: [
        "Verbos com mais de um significado",
        "Verbos com duas formas corretas no particípio",
        "Verbos que só existem no plural",
        "Verbos com mais de três sílabas",
      ],
      correctAnswer: "Verbos com duas formas corretas no particípio",
      hint: "Por exemplo, 'acender' tem as formas 'acendido' e 'aceso'.",
    },
    {
      text: "Qual é a função do gerúndio?",
      options: [
        "Expressar uma ação concluída",
        "Indicar uma ordem ou pedido",
        "Expressar uma ação em andamento",
        "Nomear uma ação",
      ],
      correctAnswer: "Expressar uma ação em andamento",
      hint: "Pense em frases como 'Estou estudando' ou 'Vou saindo'.",
    },
    {
      text: "O que caracteriza um verbo pronominal?",
      options: [
        "Sempre é conjugado na primeira pessoa",
        "Necessita de um pronome oblíquo na mesma pessoa do sujeito",
        "Não possui sujeito",
        "Só existe no infinitivo",
      ],
      correctAnswer: "Necessita de um pronome oblíquo na mesma pessoa do sujeito",
      hint: "Exemplos incluem 'arrepender-se', 'queixar-se'.",
    },
    {
      text: "Qual é a diferença entre verbos transitivos e intransitivos?",
      options: [
        "Transitivos têm sujeito, intransitivos não",
        "Transitivos existem em todos os tempos, intransitivos só no presente",
        "Transitivos precisam de complemento, intransitivos não",
        "Transitivos são regulares, intransitivos são irregulares",
      ],
      correctAnswer: "Transitivos precisam de complemento, intransitivos não",
      hint: "Compare 'O menino comeu a maçã' (transitivo) com 'O pássaro voou' (intransitivo).",
    },
  ],
  2: [
    {
      text: "Qual é a função do modo imperativo?",
      options: [
        "Expressar desejos ou possibilidades",
        "Dar ordens, conselhos ou fazer pedidos",
        "Indicar ações no passado",
        "Expressar ações habituais",
      ],
      correctAnswer: "Dar ordens, conselhos ou fazer pedidos",
      hint: "É usado em frases como 'Faça isso agora!' ou 'Por favor, venha aqui'.",
    },
    {
      text: "O que são verbos auxiliares?",
      options: [
        "Verbos que não possuem significado próprio",
        "Verbos que ajudam na conjugação de outros verbos",
        "Verbos que só existem no infinitivo",
        "Verbos que não variam em pessoa e número",
      ],
      correctAnswer: "Verbos que ajudam na conjugação de outros verbos",
      hint: "Pense em verbos como 'ter' e 'haver' em tempos compostos.",
    },
    {
      text: "Qual é a diferença entre verbos bitransitivos e transitivos diretos e indiretos?",
      options: [
        "Bitransitivos têm dois objetos, transitivos diretos e indiretos têm um objeto cada",
        "Bitransitivos só existem no presente, transitivos diretos e indiretos em todos os tempos",
        "Bitransitivos são regulares, transitivos diretos e indiretos são irregulares",
        "Não há diferença, são termos sinônimos",
      ],
      correctAnswer: "Bitransitivos têm dois objetos, transitivos diretos e indiretos têm um objeto cada",
      hint: "Compare 'Eu dei um livro (OD) ao João (OI)' com 'Eu comprei um livro (OD)' e 'Eu gosto de música (OI)'.",
    },
    {
      text: "O que é a voz passiva sintética?",
      options: [
        "Uma forma de voz ativa",
        "Uma construção com o verbo 'ser' + particípio",
        "Uma construção com o pronome 'se' + verbo na 3ª pessoa",
        "Uma forma de imperativo",
      ],
      correctAnswer: "Uma construção com o pronome 'se' + verbo na 3ª pessoa",
      hint: "Exemplo: 'Vendem-se casas' é equivalente a 'Casas são vendidas'.",
    },
    {
      text: "Qual é a função do infinitivo pessoal?",
      options: [
        "Expressar ações concluídas",
        "Indicar o sujeito da ação quando necessário",
        "Formar tempos compostos",
        "Substituir o modo subjuntivo",
      ],
      correctAnswer: "Indicar o sujeito da ação quando necessário",
      hint: "É usado em frases como 'É importante vocês fazerem o dever'.",
    },
    {
      text: "O que são verbos anômalos?",
      options: [
        "Verbos que não seguem nenhum padrão de conjugação",
        "Verbos que só existem no infinitivo",
        "Verbos que não variam em pessoa e número",
        "Verbos que têm mais de um significado",
      ],
      correctAnswer: "Verbos que não seguem nenhum padrão de conjugação",
      hint: "O verbo 'ser' é um exemplo, com formas como 'sou', 'era', 'fui'.",
    },
    {
      text: "Qual é a diferença entre verbos reflexivos e recíprocos?",
      options: [
        "Reflexivos indicam ação mútua, recíprocos ação sobre si mesmo",
        "Reflexivos indicam ação sobre si mesmo, recíprocos ação mútua",
        "Reflexivos só existem no singular, recíprocos só no plural",
        "Não há diferença, são termos sinônimos",
      ],
      correctAnswer: "Reflexivos indicam ação sobre si mesmo, recíprocos ação mútua",
      hint: "Compare 'Eu me penteei' (reflexivo) com 'Eles se abraçaram' (recíproco).",
    },
    {
      text: "O que é mesóclise?",
      options: [
        "Colocação do pronome no meio do verbo",
        "Colocação do pronome antes do verbo",
        "Colocação do pronome depois do verbo",
        "Um tipo de conjugação verbal",
      ],
      correctAnswer: "Colocação do pronome no meio do verbo",
      hint: "Ocorre em verbos no futuro do presente e do pretérito, como em 'dar-te-ei'.",
    },
    {
      text: "Qual é a função do particípio?",
      options: [
        "Expressar ações em andamento",
        "Formar tempos compostos e voz passiva",
        "Indicar ordens ou pedidos",
        "Substituir o modo subjuntivo",
      ],
      correctAnswer: "Formar tempos compostos e voz passiva",
      hint: "É usado em construções como 'Tenho estudado' e 'A carta foi enviada'.",
    },
    {
      text: "O que são verbos impessoais?",
      options: [
        "Verbos conjugados em todas as pessoas",
        "Verbos que não possuem sujeito",
        "Verbos que só existem no infinitivo",
        "Verbos que indicam sentimentos",
      ],
      correctAnswer: "Verbos que não possuem sujeito",
      hint: "Exemplos incluem verbos que indicam fenômenos da natureza, como 'chover'.",
    },
  ],
  3: [
    {
      text: "O que é aspecto verbal?",
      options: [
        "A pessoa e o número do verbo",
        "O modo como a ação é vista em relação ao seu desenvolvimento",
        "O tempo em que a ação ocorre",
        "A voz do verbo (ativa, passiva ou reflexiva)",
      ],
      correctAnswer: "O modo como a ação é vista em relação ao seu desenvolvimento",
      hint: "Pense na diferença entre 'Eu li o livro' e 'Eu estava lendo o livro'.",
    },
    {
      text: "Qual é a diferença entre o pretérito perfeito e o pretérito imperfeito?",
      options: [
        "Perfeito indica ações concluídas, imperfeito ações contínuas ou habituais no passado",
        "Perfeito é usado para ações recentes, imperfeito para ações distantes",
        "Perfeito é usado na fala, imperfeito na escrita",
        "Não há diferença, são intercambiáveis",
      ],
      correctAnswer: "Perfeito indica ações concluídas, imperfeito ações contínuas ou habituais no passado",
      hint: "Compare 'Eu comi (perfeito) quando ela chegou' com 'Eu comia (imperfeito) quando ela chegava'.",
    },
    {
      text: "O que são verbos modais?",
      options: [
        "Verbos que indicam modo ou maneira",
        "Verbos que expressam possibilidade, necessidade ou obrigação",
        "Verbos que só existem no modo indicativo",
        "Verbos que não possuem conjugação",
      ],
      correctAnswer: "Verbos que expressam possibilidade, necessidade ou obrigação",
      hint: "Exemplos incluem 'poder', 'dever', 'precisar'.",
    },
    {
      text: "Qual é a função do futuro do pretérito?",
      options: [
        "Indicar ações futuras em relação ao presente",
        "Expressar ações condicionais ou hipotéticas",
        "Formar a voz passiva",
        "Substituir o presente do indicativo",
      ],
      correctAnswer: "Expressar ações condicionais ou hipotéticas",
      hint: "É usado em frases como 'Eu faria isso se pudesse'.",
    },
    {
      text: "O que é um verbo causativo?",
      options: [
        "Um verbo que indica causa e consequência",
        "Um verbo que faz com que outro realize a ação",
        "Um verbo que só existe no modo subjuntivo",
        "Um verbo que não possui sujeito",
      ],
      correctAnswer: "Um verbo que faz com que outro realize a ação",
      hint: "Exemplos incluem 'fazer' em 'Fiz o João estudar' ou 'mandar' em 'Mandei pintar a casa'.",
    },
    {
      text: "Qual é a diferença entre verbos factitivos e sensitivos?",
      options: [
        "Factitivos indicam sensações, sensitivos indicam ações causadas",
        "Factitivos indicam ações causadas, sensitivos indicam sensações",
        "Factitivos são transitivos, sensitivos são intransitivos",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Factitivos indicam ações causadas, sensitivos indicam sensações",
      hint: "Factitivos como 'fazer' em 'fazer rir', sensitivos como 'ver' em 'ver chover'.",
    },
    {
      text: "O que é a locução verbal?",
      options: [
        "Um verbo conjugado isoladamente",
        "Dois ou mais verbos que funcionam como uma unidade de significado",
        "Um verbo no infinitivo",
        "Um verbo seguido de um advérbio",
      ],
      correctAnswer: "Dois ou mais verbos que funcionam como uma unidade de significado",
      hint: "Exemplos incluem 'vou estudar', 'estava dormindo'.",
    },
    {
      text: "Qual é a função do modo conjuntivo em português europeu?",
      options: [
        "É equivalente ao indicativo no português brasileiro",
        "É usado apenas em situações formais",
        "Corresponde ao subjuntivo no português brasileiro",
        "Não existe no português europeu",
      ],
      correctAnswer: "Corresponde ao subjuntivo no português brasileiro",
      hint: "Em Portugal, usa-se 'conjuntivo' onde no Brasil se usa 'subjuntivo'.",
    },
    {
      text: "O que são verbos vicários?",
      options: [
        "Verbos que substituem outros para evitar repetição",
        "Verbos que não possuem conjugação",
        "Verbos que indicam vícios ou hábitos",
        "Verbos que só existem no gerúndio",
      ],
      correctAnswer: "Verbos que substituem outros para evitar repetição",
      hint: "O verbo 'fazer' é comumente usado como vicário, como em 'Ele estuda muito e eu também faço'.",
    },
    {
      text: "Qual é a diferença entre o futuro do presente simples e o futuro do presente composto?",
      options: [
        "O simples indica certeza, o composto indica probabilidade",
        "O simples é formado por um verbo, o composto por dois ou mais",
        "O simples é usado na fala, o composto na escrita",
        "Não há diferença, são intercambiáveis",
      ],
      correctAnswer: "O simples é formado por um verbo, o composto por dois ou mais",
      hint: "Compare 'estudarei' (simples) com 'vou estudar' (composto).",
    },
  ],
  4: [
    {
      text: "O que é o fenômeno da derivação imprópria em verbos?",
      options: [
        "Quando um verbo muda de conjugação",
        "Quando um verbo é usado como substantivo",
        "Quando um verbo perde sua terminação",
        "Quando um verbo ganha um prefixo",
      ],
      correctAnswer: "Quando um verbo é usado como substantivo",
      hint: "Por exemplo, em 'O cantar dos pássaros', o verbo 'cantar' é usado como substantivo.",
    },
    {
      text: "O que caracteriza os verbos de elocução?",
      options: [
        "São verbos que indicam fenômenos da natureza",
        "São verbos que expressam um dizer ou uma forma de expressão",
        "São verbos que não possuem sujeito",
        "São verbos que só existem no infinitivo",
      ],
      correctAnswer: "São verbos que expressam um dizer ou uma forma de expressão",
      hint: "Exemplos incluem 'dizer', 'afirmar', 'sussurrar', 'gritar'.",
    },
    {
      text: "Qual é a função do presente gnômico?",
      options: [
        "Expressar ações que estão acontecendo no momento da fala",
        "Indicar verdades universais ou fatos científicos",
        "Formar o futuro do presente",
        "Expressar ações habituais no passado",
      ],
      correctAnswer: "Indicar verdades universais ou fatos científicos",
      hint: "É usado em frases como 'A Terra gira em torno do Sol'.",
    },
    {
      text: "O que são verbos pronominais acidentais?",
      options: [
        "Verbos que são sempre pronominais",
        "Verbos que nunca são pronominais",
        "Verbos que podem ser usados com ou sem pronome, com mudança de significado",
        "Verbos que não existem na forma pronominal",
      ],
      correctAnswer: "Verbos que podem ser usados com ou sem pronome, com mudança de significado",
      hint: "Por exemplo, 'lembrar' (recordar algo) e 'lembrar-se' (recordar-se de algo).",
    },
    {
      text: "Qual é a diferença entre verbos perfectivos e imperfectivos?",
      options: [
        "Perfectivos indicam ações concluídas, imperfectivos ações em curso ou habituais",
        "Perfectivos são regulares, imperfectivos são irregulares",
        "Perfectivos são transitivos, imperfectivos são intransitivos",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Perfectivos indicam ações concluídas, imperfectivos ações em curso ou habituais",
      hint: "Compare 'Ele leu o livro' (perfectivo) com 'Ele lia muito quando criança' (imperfectivo).",
    },
    {
      text: "O que é um verbo suporte?",
      options: [
        "Um verbo que não possui significado próprio",
        "Um verbo que ajuda na formação de tempos compostos",
        "Um verbo que forma uma unidade semântica com um nome ou adjetivo",
        "Um verbo que só existe no modo subjuntivo",
      ],
      correctAnswer: "Um verbo que forma uma unidade semântica com um nome ou adjetivo",
      hint: "Exemplos incluem 'dar' em 'dar um passeio' ou 'fazer' em 'fazer uma pergunta'.",
    },
    {
      text: "Qual é a função do presente histórico?",
      options: [
        "Narrar fatos passados como se estivessem acontecendo no presente",
        "Expressar ações futuras",
        "Indicar ações habituais",
        "Formar a voz passiva",
      ],
      correctAnswer: "Narrar fatos passados como se estivessem acontecendo no presente",
      hint: "É comum em narrativas históricas ou jornalísticas para dar mais vivacidade ao relato.",
    },
    {
      text: "O que são verbos incoativos?",
      options: [
        "Verbos que indicam o início de uma ação ou mudança de estado",
        "Verbos que indicam o fim de uma ação",
        "Verbos que não possuem sujeito",
        "Verbos que só existem no particípio",
      ],
      correctAnswer: "Verbos que indicam o início de uma ação ou mudança de estado",
      hint: "Exemplos incluem 'amanhecer', 'envelhecer', 'adormecer'.",
    },
    {
      text: "Qual é a diferença entre o futuro do subjuntivo e o infinitivo pessoal?",
      options: [
        "O futuro do subjuntivo é usado em orações subordinadas, o infinitivo pessoal em orações principais",
        "O futuro do subjuntivo expressa possibilidade, o infinitivo pessoal expressa certeza",
        "O futuro do subjuntivo é conjugado, o infinitivo pessoal não varia",
        "Não há diferença, são intercambiáveis",
      ],
      correctAnswer:
        "O futuro do subjuntivo é usado em orações subordinadas, o infinitivo pessoal em orações principais",
      hint: "Compare 'Quando eu fizer (fut. subj.) o jantar...' com 'É importante fazermos (inf. pessoal) o jantar'.",
    },
    {
      text: "O que é a perífrase verbal?",
      options: [
        "Um verbo conjugado isoladamente",
        "Uma locução verbal que expressa um aspecto específico da ação",
        "Um verbo no particípio",
        "Um verbo seguido de um advérbio",
      ],
      correctAnswer: "Uma locução verbal que expressa um aspecto específico da ação",
      hint: "Exemplos incluem 'estar + gerúndio' para expressar uma ação em andamento.",
    },
  ],
  5: [
    {
      text: "O que é o fenômeno da haplologia em verbos?",
      options: [
        "A repetição de sílabas em um verbo",
        "A supressão de uma sílaba semelhante à seguinte",
        "A adição de uma sílaba a um verbo",
        "A troca de ordem das sílabas em um verbo",
      ],
      correctAnswer: "A supressão de uma sílaba semelhante à seguinte",
      hint: "Ocorre em formas como 'tragamos' em vez de 'trazigamos' do verbo 'trazer'.",
    },
    {
      text: "Qual é a função do presente jussivo?",
      options: [
        "Expressar um desejo ou ordem",
        "Indicar uma ação habitual",
        "Narrar fatos passados",
        "Formar a voz passiva",
      ],
      correctAnswer: "Expressar um desejo ou ordem",
      hint: "É usado em frases como 'Venham todos para a sala agora!'.",
    },
    {
      text: "O que são verbos frequentativos?",
      options: [
        "Verbos que indicam ações realizadas com frequência ou repetidamente",
        "Verbos que só podem ser usados uma vez em cada frase",
        "Verbos que indicam ações raras",
        "Verbos que não possuem conjugação",
      ],
      correctAnswer: "Verbos que indicam ações realizadas com frequência ou repetidamente",
      hint: "Exemplos incluem 'saltitar' (saltar repetidamente) e 'beijocar' (beijar repetidamente).",
    },
    {
      text: "Qual é a diferença entre o gerúndio e o particípio presente?",
      options: [
        "O gerúndio termina em -ndo, o particípio presente em -nte",
        "O gerúndio é uma forma nominal, o particípio presente não existe em português",
        "O gerúndio indica ações passadas, o particípio presente ações presentes",
        "Não há diferença, são a mesma coisa",
      ],
      correctAnswer: "O gerúndio termina em -ndo, o particípio presente em -nte",
      hint: "Compare 'estudando' (gerúndio) com 'estudante' (particípio presente usado como adjetivo ou substantivo).",
    },
    {
      text: "O que é a silepse de pessoa em verbos?",
      options: [
        "A concordância do verbo com o sentido, não com a forma gramatical do sujeito",
        "A repetição desnecessária do sujeito",
        "A omissão do sujeito",
        "A concordância do verbo com o objeto, não com o sujeito",
      ],
      correctAnswer: "A concordância do verbo com o sentido, não com a forma gramatical do sujeito",
      hint: "Ocorre em frases como 'Os brasileiros somos todos apaixonados por futebol'.",
    },
    {
      text: "Qual é a função do infinitivo pessoal composto?",
      options: [
        "Indicar uma ação futura",
        "Expressar uma ação anterior a outra no passado",
        "Formar a voz passiva",
        "Substituir o presente do indicativo",
      ],
      correctAnswer: "Expressar uma ação anterior a outra no passado",
      hint: "É usado em frases como 'Depois de termos estudado, fomos ao cinema'.",
    },
    {
      text: "O que são verbos performativos?",
      options: [
        "Verbos que descrevem uma performance artística",
        "Verbos que realizam a ação que expressam ao serem pronunciados",
        "Verbos que só existem no infinitivo",
        "Verbos que indicam movimento físico",
      ],
      correctAnswer: "Verbos que realizam a ação que expressam ao serem pronunciados",
      hint: "Exemplos incluem 'prometer', 'declarar', 'batizar' quando usados na primeira pessoa do presente.",
    },
    {
      text: "Qual é a diferença entre verbos ergativos e verbos transitivos?",
      options: [
        "Ergativos podem ser usados intransitivamente com sujeito paciente, transitivos não",
        "Ergativos são sempre intransitivos, transitivos sempre precisam de objeto",
        "Ergativos são irregulares, transitivos são regulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Ergativos podem ser usados intransitivamente com sujeito paciente, transitivos não",
      hint: "Compare 'O vento quebrou o galho' e 'O galho quebrou' (ergativo) com 'João comeu a maçã' (transitivo).",
    },
    {
      text: "O que é o aspecto cessativo em verbos?",
      options: [
        "Indica o início de uma ação",
        "Indica a continuidade de uma ação",
        "Indica o término ou a interrupção de uma ação",
        "Indica a repetição de uma ação",
      ],
      correctAnswer: "Indica o término ou a interrupção de uma ação",
      hint: "É expresso por perífrases como 'deixar de', 'parar de', como em 'Ele deixou de fumar'.",
    },
    {
      text: "Qual é a função do presente omnitemporal?",
      options: [
        "Expressar ações que ocorrem apenas no presente",
        "Indicar verdades eternas ou atemporais",
        "Formar o futuro do presente",
        "Substituir o pretérito perfeito",
      ],
      correctAnswer: "Indicar verdades eternas ou atemporais",
      hint: "É usado em provérbios ou afirmações científicas, como 'A água ferve a 100°C'.",
    },
  ],
  6: [
    {
      text: "O que é a tmese em verbos?",
      options: [
        "A separação de um verbo composto por um pronome",
        "A junção de dois verbos para formar um novo",
        "A omissão de um verbo em uma frase",
        "A repetição de um verbo para dar ênfase",
      ],
      correctAnswer: "A separação de um verbo composto por um pronome",
      hint: "Ocorre em construções como 'dar-te-ei' (te darei) ou 'amar-te-ia' (te amaria).",
    },
    {
      text: "Qual é a função do modo potencial em algumas línguas?",
      options: [
        "Expressar certeza absoluta",
        "Indicar possibilidade ou probabilidade",
        "Formar a voz passiva",
        "Substituir o modo imperativo",
      ],
      correctAnswer: "Indicar possibilidade ou probabilidade",
      hint: "Em português, esse modo é geralmente expresso pelo futuro do pretérito, como em 'Ele poderia chegar a qualquer momento'.",
    },
    {
      text: "O que são verbos meteorológicos?",
      options: [
        "Verbos que descrevem o clima ou fenômenos atmosféricos",
        "Verbos que indicam medidas ou quantidades",
        "Verbos que só existem no modo subjuntivo",
        "Verbos que expressam emoções",
      ],
      correctAnswer: "Verbos que descrevem o clima ou fenômenos atmosféricos",
      hint: "Exemplos incluem 'chover', 'nevar', 'trovejar'.",
    },
    {
      text: "Qual é a diferença entre o aspecto iterativo e o aspecto habitual?",
      options: [
        "Iterativo indica repetição pontual, habitual indica costume ou frequência",
        "Iterativo é usado no passado, habitual no presente",
        "Iterativo é para verbos regulares, habitual para irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Iterativo indica repetição pontual, habitual indica costume ou frequência",
      hint: "Compare 'Ele bateu na porta várias vezes' (iterativo) com 'Ele sempre acorda cedo' (habitual).",
    },
    {
      text: "O que é a derivação regressiva em verbos?",
      options: [
        "Formação de um verbo a partir de um substantivo ou adjetivo",
        "Formação de um substantivo a partir de um verbo",
        "Adição de um prefixo a um verbo",
        "Conjugação de um verbo no tempo passado",
      ],
      correctAnswer: "Formação de um substantivo a partir de um verbo",
      hint: "Exemplos incluem 'abraço' (de abraçar), 'grito' (de gritar).",
    },
    {
      text: "Qual é a função do presente conativo?",
      options: [
        "Expressar uma tentativa ou esforço para realizar uma ação",
        "Indicar uma ação habitual",
        "Narrar fatos passados",
        "Formar o futuro do presente",
      ],
      correctAnswer: "Expressar uma tentativa ou esforço para realizar uma ação",
      hint: "É usado em frases como 'Há horas que tento resolver este problema'.",
    },
    {
      text: "O que são verbos dicendi?",
      options: [
        "Verbos que expressam ordem ou comando",
        "Verbos que indicam fala ou declaração",
        "Verbos que descrevem ações físicas",
        "Verbos que expressam sentimentos",
      ],
      correctAnswer: "Verbos que indicam fala ou declaração",
      hint: "Exemplos incluem 'dizer', 'afirmar', 'declarar', 'sussurrar'.",
    },
    {
      text: "Qual é a diferença entre verbos plenos e verbos vazios?",
      options: [
        "Plenos têm significado próprio, vazios dependem de outros elementos",
        "Plenos são transitivos, vazios são intransitivos",
        "Plenos são regulares, vazios são irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Plenos têm significado próprio, vazios dependem de outros elementos",
      hint: "Compare 'comer' (pleno) com 'dar' em 'dar um passeio' (vazio).",
    },
    {
      text: "O que é o fenômeno da sândi em verbos?",
      options: [
        "A mudança fonética na junção de palavras",
        "A omissão de um verbo em uma frase",
        "A repetição de um verbo para dar ênfase",
        "A conjugação incorreta de um verbo",
      ],
      correctAnswer: "A mudança fonética na junção de palavras",
      hint: "Ocorre em casos como 'faze-lo' (fazê-lo) ou 'di-lo-ei' (direi-o).",
    },
    {
      text: "Qual é a função do infinitivo pessoal em português?",
      options: [
        "Expressar ações sem sujeito definido",
        "Indicar o sujeito da ação quando necessário",
        "Formar tempos compostos",
        "Substituir o modo subjuntivo",
      ],
      correctAnswer: "Indicar o sujeito da ação quando necessário",
      hint: "É usado em frases como 'É importante vocês chegarem cedo'.",
    },
  ],
  7: [
    {
      text: "O que é a morfologia verbal?",
      options: [
        "O estudo da conjugação dos verbos",
        "O estudo da formação e estrutura dos verbos",
        "O estudo do significado dos verbos",
        "O estudo da origem histórica dos verbos",
      ],
      correctAnswer: "O estudo da formação e estrutura dos verbos",
      hint: "Inclui o estudo de radicais, desinências, vogais temáticas e outros elementos que compõem os verbos.",
    },
    {
      text: "Qual é a função do modo optativo em algumas línguas?",
      options: [
        "Expressar um desejo ou vontade",
        "Indicar uma ordem ou comando",
        "Formar a voz passiva",
        "Substituir o modo indicativo",
      ],
      correctAnswer: "Expressar um desejo ou vontade",
      hint: "Em português, essa função é geralmente expressa pelo subjuntivo, como em 'Que você seja feliz!'.",
    },
    {
      text: "O que são verbos denominativos?",
      options: [
        "Verbos formados a partir de substantivos ou adjetivos",
        "Verbos que dão nome a algo",
        "Verbos que só existem no infinitivo",
        "Verbos que indicam quantidade",
      ],
      correctAnswer: "Verbos formados a partir de substantivos ou adjetivos",
      hint: "Exemplos incluem 'alfabetizar' (de alfabeto) ou 'escurecer' (de escuro).",
    },
    {
      text: "Qual é a diferença entre o aspecto incoativo e o aspecto inceptivo?",
      options: [
        "Incoativo indica o início gradual, inceptivo o início pontual de uma ação",
        "Incoativo é usado no passado, inceptivo no presente",
        "Incoativo é para verbos regulares, inceptivo para irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Incoativo indica o início gradual, inceptivo o início pontual de uma ação",
      hint: "Compare 'A criança começou a andar' (inceptivo) com 'O céu começou a escurecer' (incoativo).",
    },
    {
      text: "O que é a parassíntese verbal?",
      options: [
        "A formação de um verbo por prefixação e sufixação simultâneas",
        "A separação de um verbo em duas palavras",
        "A conjugação de dois verbos ao mesmo tempo",
        "A omissão de um verbo em uma frase",
      ],
      correctAnswer: "A formação de um verbo por prefixação e sufixação simultâneas",
      hint: "Exemplos incluem 'entristecer' (en + triste + ecer) ou 'anoitecer' (a + noite + ecer).",
    },
    {
      text: "Qual é a função do presente durativo?",
      options: [
        "Expressar uma ação que está em curso no momento da fala",
        "Indicar uma ação habitual",
        "Narrar fatos passados",
        "Formar o futuro do presente",
      ],
      correctAnswer: "Expressar uma ação que está em curso no momento da fala",
      hint: "É frequentemente expresso pela perífrase 'estar + gerúndio', como em 'Estou estudando agora'.",
    },
    {
      text: "O que são verbos perceptivos?",
      options: [
        "Verbos que expressam percepções sensoriais",
        "Verbos que indicam ações mentais",
        "Verbos que descrevem movimentos físicos",
        "Verbos que expressam emoções",
      ],
      correctAnswer: "Verbos que expressam percepções sensoriais",
      hint: "Exemplos incluem 'ver', 'ouvir', 'sentir', 'cheirar', 'provar'.",
    },
    {
      text: "Qual é a diferença entre verbos defectivos e verbos abundantes?",
      options: [
        "Defectivos faltam formas, abundantes têm formas extras",
        "Defectivos são regulares, abundantes são irregulares",
        "Defectivos são transitivos, abundantes são intransitivos",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Defectivos faltam formas, abundantes têm formas extras",
      hint: "Compare 'abolir' (defectivo, falta algumas conjugações) com 'aceitar' (abundante, tem duas formas de particípio).",
    },
    {
      text: "O que é o fenômeno da hipercorreção em verbos?",
      options: [
        "A correção excessiva levando a erros",
        "A conjugação correta de verbos irregulares",
        "A simplificação da conjugação verbal",
        "A criação de novos verbos",
      ],
      correctAnswer: "A correção excessiva levando a erros",
      hint: "Ocorre quando alguém diz, por exemplo, 'eu fazi' tentando corrigir o que acredita ser um erro em 'eu fiz'.",
    },
    {
      text: "Qual é a função do modo condicional em algumas línguas?",
      options: [
        "Expressar ações que dependem de uma condição",
        "Indicar ordens ou pedidos",
        "Formar a voz passiva",
        "Substituir o modo indicativo",
      ],
      correctAnswer: "Expressar ações que dependem de uma condição",
      hint: "Em português, essa função é geralmente expressa pelo futuro do pretérito, como em 'Eu iria se pudesse'.",
    },
  ],
  8: [
    {
      text: "O que é a supletividade verbal?",
      options: [
        "A formação de tempos verbais com radicais diferentes",
        "A conjugação regular de verbos irregulares",
        "A criação de novos verbos a partir de outros",
        "A simplificação da conjugação verbal",
      ],
      correctAnswer: "A formação de tempos verbais com radicais diferentes",
      hint: "Ocorre em verbos como 'ir' (vou, fui) ou 'ser' (sou, era, fui).",
    },
    {
      text: "Qual é a função do aspecto resultativo?",
      options: [
        "Indicar o resultado ou estado resultante de uma ação",
        "Expressar uma ação em andamento",
        "Mostrar o início de uma ação",
        "Indicar a repetição de uma ação",
      ],
      correctAnswer: "Indicar o resultado ou estado resultante de uma ação",
      hint: "É expresso por construções como 'estar + particípio', como em 'A casa está pintada'.",
    },
    {
      text: "O que são verbos bitransitivos?",
      options: [
        "Verbos que exigem dois complementos: um objeto direto e um indireto",
        "Verbos que podem ser usados transitiva ou intransitivamente",
        "Verbos que têm dois significados diferentes",
        "Verbos que se conjugam em duas vozes diferentes",
      ],
      correctAnswer: "Verbos que exigem dois complementos: um objeto direto e um indireto",
      hint: "Exemplos incluem 'dar' em 'Dei um livro ao João' ou 'enviar' em 'Enviei uma carta à minha mãe'.",
    },
    {
      text: "Qual é a diferença entre o particípio passado e o particípio presente?",
      options: [
        "Passado indica ação concluída, presente indica ação em curso",
        "Passado é usado em tempos compostos, presente não existe em português",
        "Passado é regular, presente é sempre irregular",
        "Não há diferença, são a mesma coisa",
      ],
      correctAnswer: "Passado indica ação concluída, presente indica ação em curso",
      hint: "Compare 'feito' (particípio passado) com 'falante' (particípio presente usado como adjetivo).",
    },
    {
      text: "O que é a nominalização de verbos?",
      options: [
        "O processo de transformar verbos em substantivos",
        "A conjugação de verbos em todos os tempos",
        "A criação de novos verbos a partir de substantivos",
        "A simplificação da estrutura verbal",
      ],
      correctAnswer: "O processo de transformar verbos em substantivos",
      hint: "Exemplos incluem 'cantar' → 'o canto', 'vender' → 'a venda'.",
    },
    {
      text: "Qual é a função do presente progressivo?",
      options: [
        "Expressar uma ação em andamento no momento da fala",
        "Indicar uma ação habitual",
        "Narrar fatos passados",
        "Formar o futuro do presente",
      ],
      correctAnswer: "Expressar uma ação em andamento no momento da fala",
      hint: "É formado com 'estar + gerúndio', como em 'Estou trabalhando agora'.",
    },
    {
      text: "O que são verbos copulativos?",
      options: [
        "Verbos que ligam o sujeito ao predicativo",
        "Verbos que indicam ações recíprocas",
        "Verbos que expressam fenômenos da natureza",
        "Verbos que só existem no infinitivo",
      ],
      correctAnswer: "Verbos que ligam o sujeito ao predicativo",
      hint: "Exemplos incluem 'ser', 'estar', 'parecer', 'permanecer'.",
    },
    {
      text: "Qual é a diferença entre verbos factitivos e verbos causativos?",
      options: [
        "Factitivos fazem alguém realizar uma ação, causativos fazem algo acontecer",
        "Factitivos são transitivos, causativos são intransitivos",
        "Factitivos são regulares, causativos são irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Factitivos fazem alguém realizar uma ação, causativos fazem algo acontecer",
      hint: "Compare 'O chefe fez os funcionários trabalharem' (factitivo) com 'O sol fez a neve derreter' (causativo).",
    },
    {
      text: "O que é o fenômeno da gramaticalização em verbos?",
      options: [
        "O processo pelo qual verbos lexicais se tornam auxiliares ou partículas gramaticais",
        "A criação de novos verbos a partir de outras classes gramaticais",
        "A conjugação regular de verbos irregulares",
        "A simplificação da estrutura verbal",
      ],
      correctAnswer: "O processo pelo qual verbos lexicais se tornam auxiliares ou partículas gramaticais",
      hint: "Um exemplo é o verbo 'ir' usado como auxiliar de futuro em 'vou fazer' em vez de seu significado original de movimento.",
    },
    {
      text: "Qual é a função do modo subjuntivo-optativo em algumas línguas?",
      options: [
        "Expressar desejos, possibilidades ou situações hipotéticas",
        "Indicar ordens ou comandos diretos",
        "Formar a voz passiva",
        "Substituir o modo indicativo em todas as situações",
      ],
      correctAnswer: "Expressar desejos, possibilidades ou situações hipotéticas",
      hint: "Em português, essa função é geralmente coberta pelo modo subjuntivo, como em 'Espero que ele venha' ou 'Que seja feita a sua vontade'.",
    },
  ],
  9: [
    {
      text: "O que é a alternância vocálica em verbos?",
      options: [
        "A mudança da vogal do radical em certas conjugações",
        "A troca de posição entre duas vogais em um verbo",
        "A adição de uma vogal no final do verbo",
        "A eliminação de vogais em verbos longos",
      ],
      correctAnswer: "A mudança da vogal do radical em certas conjugações",
      hint: "Ocorre em verbos como 'dormir' (durmo, dormes) ou 'medir' (meço, medes).",
    },
    {
      text: "Qual é a função do aspecto semelfactivo?",
      options: [
        "Indicar uma ação que ocorre uma única vez",
        "Expressar uma ação habitual",
        "Mostrar o início de uma ação",
        "Indicar a repetição contínua de uma ação",
      ],
      correctAnswer: "Indicar uma ação que ocorre uma única vez",
      hint: "Em português, pode ser expresso por verbos como 'piscar', 'tossir' quando se referem a uma única ocorrência.",
    },
    {
      text: "O que são verbos leves?",
      options: [
        "Verbos com pouco peso semântico que formam predicados com nomes",
        "Verbos que indicam ações simples ou fáceis",
        "Verbos que têm poucas letras",
        "Verbos que só existem no infinitivo",
      ],
      correctAnswer: "Verbos com pouco peso semântico que formam predicados com nomes",
      hint: "Exemplos incluem 'dar' em 'dar um passeio' ou 'fazer' em 'fazer uma pergunta'.",
    },
    {
      text: "Qual é a diferença entre o aspecto perfectivo e o aspecto imperfectivo?",
      options: [
        "Perfectivo vê a ação como completa, imperfectivo como em desenvolvimento",
        "Perfectivo é usado no passado, imperfectivo no presente",
        "Perfectivo é para verbos regulares, imperfectivo para irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Perfectivo vê a ação como completa, imperfectivo como em desenvolvimento",
      hint: "Compare 'Ele leu o livro' (perfectivo) com 'Ele estava lendo o livro' (imperfectivo).",
    },
    {
      text: "O que é a incorporação nominal em verbos?",
      options: [
        "O processo de incluir um objeto nominal na forma do verbo",
        "A transformação de substantivos em verbos",
        "A adição de prefixos nominais a verbos",
        "A conjugação de verbos em todos os tempos nominais",
      ],
      correctAnswer: "O processo de incluir um objeto nominal na forma do verbo",
      hint: "Embora raro em português, pode ser visto em palavras como 'maltratar' (tratar mal).",
    },
    {
      text: "Qual é a função do presente histórico?",
      options: [
        "Narrar eventos passados como se estivessem acontecendo no presente",
        "Indicar ações que sempre acontecem",
        "Expressar planos para o futuro",
        "Formar o pretérito perfeito",
      ],
      correctAnswer: "Narrar eventos passados como se estivessem acontecendo no presente",
      hint: "É usado para dar vivacidade à narrativa, como em 'Em 1500, Cabral chega ao Brasil'.",
    },
    {
      text: "O que são verbos modais?",
      options: [
        "Verbos que expressam modalidade (possibilidade, necessidade, etc.)",
        "Verbos que indicam moda ou tendência",
        "Verbos que só existem no modo indicativo",
        "Verbos que expressam emoções",
      ],
      correctAnswer: "Verbos que expressam modalidade (possibilidade, necessidade, etc.)",
      hint: "Exemplos incluem 'poder', 'dever', 'precisar'.",
    },
    {
      text: "Qual é a diferença entre verbos télicos e atélicos?",
      options: [
        "Télicos têm um ponto final definido, atélicos não",
        "Télicos são transitivos, atélicos são intransitivos",
        "Télicos são regulares, atélicos são irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Télicos têm um ponto final definido, atélicos não",
      hint: "Compare 'construir uma casa' (télico, tem um fim definido) com 'correr' (atélico, pode continuar indefinidamente).",
    },
    {
      text: "O que é o fenômeno da reanálise em verbos?",
      options: [
        "A reinterpretação da estrutura sintática de uma expressão",
        "A conjugação incorreta de verbos irregulares",
        "A criação de novos verbos a partir de outros",
        "A simplificação da conjugação verbal",
      ],
      correctAnswer: "A reinterpretação da estrutura sintática de uma expressão",
      hint: "Um exemplo histórico é a formação do futuro em línguas românicas, onde 'cantar hei' se tornou 'cantarei'.",
    },
    {
      text: "Qual é a função do modo irrealis em algumas línguas?",
      options: [
        "Expressar situações não reais ou hipotéticas",
        "Indicar ações que realmente aconteceram",
        "Formar a voz passiva",
        "Substituir o modo indicativo em todas as situações",
      ],
      correctAnswer: "Expressar situações não reais ou hipotéticas",
      hint: "Em português, essa função é geralmente coberta pelo subjuntivo e condicional, como em 'Se eu fosse rico, viajaria o mundo'.",
    },
  ],
  10: [
    {
      text: "O que é a serialização verbal?",
      options: [
        "Uma sequência de verbos que atuam como um único predicado",
        "A conjugação de verbos em série",
        "A repetição do mesmo verbo várias vezes",
        "A criação de novos verbos a partir de uma série",
      ],
      correctAnswer: "Uma sequência de verbos que atuam como um único predicado",
      hint: "Embora não comum em português, pode ser vista em construções como 'vou tentar começar a estudar'.",
    },
    {
      text: "Qual é a função do aspecto prospectivo?",
      options: [
        "Indicar uma ação que está prestes a acontecer",
        "Expressar uma ação que aconteceu no passado distante",
        "Mostrar uma ação que acontece repetidamente",
        "Indicar uma ação que acontece no presente",
      ],
      correctAnswer: "Indicar uma ação que está prestes a acontecer",
      hint: "Em português, pode ser expresso por construções como 'estar para' ou 'estar prestes a', como em 'Estou para sair'.",
    },
    {
      text: "O que são verbos de controle?",
      options: [
        "Verbos que determinam o sujeito não expresso de um verbo no infinitivo",
        "Verbos que controlam outros verbos na frase",
        "Verbos que expressam domínio ou poder",
        "Verbos que só podem ser usados no imperativo",
      ],
      correctAnswer: "Verbos que determinam o sujeito não expresso de um verbo no infinitivo",
      hint: "Exemplos incluem 'querer' em 'João quer sair' (João é o sujeito implícito de 'sair').",
    },
    {
      text: "Qual é a diferença entre o aspecto progressivo e o aspecto habitual?",
      options: [
        "Progressivo indica ação em curso, habitual indica ação recorrente",
        "Progressivo é usado no presente, habitual no passado",
        "Progressivo é para verbos regulares, habitual para irregulares",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Progressivo indica ação em curso, habitual indica ação recorrente",
      hint: "Compare 'Estou estudando agora' (progressivo) com 'Estudo todas as noites' (habitual).",
    },
    {
      text: "O que é a cliticização em verbos?",
      options: [
        "O processo pelo qual um pronome se torna dependente fonologicamente do verbo",
        "A transformação de verbos em clíticos",
        "A adição de sufixos a verbos",
        "A conjugação de verbos em todos os tempos",
      ],
      correctAnswer: "O processo pelo qual um pronome se torna dependente fonologicamente do verbo",
      hint: "Ocorre em construções como 'diga-me', onde 'me' é um clítico ligado ao verbo 'diga'.",
    },
    {
      text: "Qual é a função do presente gnômico?",
      options: [
        "Expressar verdades universais ou fatos científicos",
        "Indicar ações que estão acontecendo no momento da fala",
        "Narrar eventos históricos",
        "Formar o futuro do presente",
      ],
      correctAnswer: "Expressar verdades universais ou fatos científicos",
      hint: "É usado em frases como 'A água ferve a 100°C' ou 'O Sol nasce no leste'.",
    },
    {
      text: "O que são verbos de alçamento?",
      options: [
        "Verbos que permitem que o sujeito de uma oração subordinada se torne sujeito da oração principal",
        "Verbos que indicam movimento para cima",
        "Verbos que só podem ser usados em contextos formais",
        "Verbos que expressam aumento ou elevação",
      ],
      correctAnswer: "Verbos que permitem que o sujeito de uma oração subordinada se torne sujeito da oração principal",
      hint: "Um exemplo é 'parecer' em 'João parece estar doente' (comparado com 'Parece que João está doente').",
    },
    {
      text: "Qual é a diferença entre verbos simétricos e assimétricos?",
      options: [
        "Simétricos permitem inversão de argumentos, assimétricos não",
        "Simétricos são regulares, assimétricos são irregulares",
        "Simétricos são transitivos, assimétricos são intransitivos",
        "Não há diferença, são sinônimos",
      ],
      correctAnswer: "Simétricos permitem inversão de argumentos, assimétricos não",
      hint: "Compare 'João casou com Maria' e 'Maria casou com João' (simétrico) com 'João venceu Maria' (assimétrico).",
    },
    {
      text: "O que é o fenômeno da lexicalização em verbos?",
      options: [
        "O processo pelo qual uma expressão se torna uma unidade lexical",
        "A criação de novos verbos a partir de substantivos",
        "A conjugação de verbos em todos os tempos",
        "A simplificação da estrutura verbal",
      ],
      correctAnswer: "O processo pelo qual uma expressão se torna uma unidade lexical",
      hint: "Um exemplo é 'dar-se conta', que funciona como uma unidade de significado ('perceber').",
    },
    {
      text: "Qual é a função do modo evidencial em algumas línguas?",
      options: [
        "Indicar a fonte da informação ou o grau de certeza do falante",
        "Expressar ordens ou comandos",
        "Formar a voz passiva",
        "Substituir o modo indicativo em todas as situações",
      ],
      correctAnswer: "Indicar a fonte da informação ou o grau de certeza do falante",
      hint: "Embora não exista como modo verbal em português, pode ser expresso por advérbios como 'aparentemente' ou 'supostamente'.",
    },
  ],
}

export default allQuestions

